C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\Library\Scripts\python.exe "C:/Users/True._.Mary/AppData/Local/Programs/PyCharm Professional/plugins/python/helpers/pycharm/_jb_pytest_runner.py" --target test_objects.py::TestObjects.test_get_objects_id_param 
Testing started at 14:46 ...
Launching pytest with arguments test_objects.py::TestObjects::test_get_objects_id_param --no-header --no-summary -q in C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\tests

============================= test session starts =============================
collecting ... collected 2 items

test_objects.py::TestObjects::test_get_objects_id_param[param0] 
test_objects.py::TestObjects::test_get_objects_id_param[param1] 

============================== 2 failed in 1.75s ==============================
FAILED   [ 50%]
tests\test_objects.py:36 (TestObjects.test_get_objects_id_param[param0])
self = <test_objects.TestObjects object at 0x000001E4D377BEE0>
client = <api.api_client.ApiClient object at 0x000001E4D3779F30>
request = <FixtureRequest for <Function test_get_objects_id_param[param0]>>
param = {'ids': [1], 'index': 0}

    @pytest.mark.parametrize("param", [{"index": 0, "ids": [1]}, {"index": 1, "ids": [1, 2]}])
    def test_get_objects_id_param(self, client, request, param):
        """
        получение заранее заготовленных объектов из базы с параметром ids,
        GET /objects
        """
        # получаем массив объектов с определенными айдишниками
        response = get_objects(client, *param['ids'])
    
        # убеждаемся, что в ответ пришли именно те объекты, id которых мы запросили
        assert_status_code(response, HTTPStatus.OK)
>       should_be_valid_objects_response(request, response, param)

C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\tests\test_objects.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\assertions\objects_assertion.py:12: in should_be_valid_objects_response
    assert_response_body_value(response, exp_len, act_len,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

response = <Response [200 OK]>, exp = 1, act = 0
text = 'ОЖИДАЕМОЕ КОЛИЧЕСТВО ОБЪЕКТОВ НЕ СОВПАЛО С ФАКТИЧЕСКИМ'

    def assert_response_body_value(response, exp, act, text=None):
        """
        проверяет ответ от сервера, сравнивая полученное значение с ожидаемым для тела запроса
        :param response: ответ от сервера
        :param exp: ожидаемое значение
        :param act: полученное значение
        :param text: дополнительный текст, который необходимо вывести при несовпадении exp и act
        """
>       assert exp == act, BodyValueLogMsg(response) \
            .add_error_info(text) \
            .add_compare_result(exp, act) \
            .add_request_url() \
            .add_response_info() \
            .get_message()
E       AssertionError: 
E       ОЖИДАЕМОЕ КОЛИЧЕСТВО ОБЪЕКТОВ НЕ СОВПАЛО С ФАКТИЧЕСКИМ
E       	exptected: 1
E       	actual: 0
E       Содержимое отправляемого запроса (url, query params, тело):
E       	URL: https://api.restful-api.dev/objects?id=1
E       	method: GET
E       	headers: {'host': 'api.restful-api.dev', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.24.1'}
E       	query params:
E       	body:
E       Тело ответа:
E       	b'[]'

C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\assertions\assertion_base.py:173: AssertionError
FAILED   [100%]
tests\test_objects.py:36 (TestObjects.test_get_objects_id_param[param1])
self = <test_objects.TestObjects object at 0x000001E4D377AC80>
client = <api.api_client.ApiClient object at 0x000001E4D3779F30>
request = <FixtureRequest for <Function test_get_objects_id_param[param1]>>
param = {'ids': [1, 2], 'index': 1}

    @pytest.mark.parametrize("param", [{"index": 0, "ids": [1]}, {"index": 1, "ids": [1, 2]}])
    def test_get_objects_id_param(self, client, request, param):
        """
        получение заранее заготовленных объектов из базы с параметром ids,
        GET /objects
        """
        # получаем массив объектов с определенными айдишниками
        response = get_objects(client, *param['ids'])
    
        # убеждаемся, что в ответ пришли именно те объекты, id которых мы запросили
        assert_status_code(response, HTTPStatus.OK)
>       should_be_valid_objects_response(request, response, param)

C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\tests\test_objects.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\assertions\objects_assertion.py:12: in should_be_valid_objects_response
    assert_response_body_value(response, exp_len, act_len,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

response = <Response [200 OK]>, exp = 2, act = 0
text = 'ОЖИДАЕМОЕ КОЛИЧЕСТВО ОБЪЕКТОВ НЕ СОВПАЛО С ФАКТИЧЕСКИМ'

    def assert_response_body_value(response, exp, act, text=None):
        """
        проверяет ответ от сервера, сравнивая полученное значение с ожидаемым для тела запроса
        :param response: ответ от сервера
        :param exp: ожидаемое значение
        :param act: полученное значение
        :param text: дополнительный текст, который необходимо вывести при несовпадении exp и act
        """
>       assert exp == act, BodyValueLogMsg(response) \
            .add_error_info(text) \
            .add_compare_result(exp, act) \
            .add_request_url() \
            .add_response_info() \
            .get_message()
E       AssertionError: 
E       ОЖИДАЕМОЕ КОЛИЧЕСТВО ОБЪЕКТОВ НЕ СОВПАЛО С ФАКТИЧЕСКИМ
E       	exptected: 2
E       	actual: 0
E       Содержимое отправляемого запроса (url, query params, тело):
E       	URL: https://api.restful-api.dev/objects?id=1&id=2
E       	method: GET
E       	headers: {'host': 'api.restful-api.dev', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.24.1'}
E       	query params:
E       	body:
E       Тело ответа:
E       	b'[]'

C:\Users\True._.Mary\PycharmProjects\fin-quality-management\Lab1\assertions\assertion_base.py:173: AssertionError

Process finished with exit code 1
